FROM centos:7

RUN yum install httpd -y

WORKDIR /var/www/html/admision

COPY admision .

ENV contenido Hola mundo

RUN echo "$contenido" > /var/www/html/admision/prueba.html  

CMD apachectl -DFOREGROUND

